spring.datasource.url=jdbc:postgresql://localhost:5432/spring_11-200
spring.datasource.username=postgres
spring.datasource.password=Arlet_0804
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update